name: Deploy Infrastructure

on:
  push:
    branches: [ main ]
    paths: 
      - 'infrastructure/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'infrastructure/**'

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: infrastructure

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.0

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format Check
      run: terraform fmt -check

    - name: Terraform Plan (Production)
      if: github.event_name == 'pull_request'
      run: terraform plan -var-file="environments/prod.tfvars" -no-color

    - name: Terraform Apply (Production)
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -var-file="environments/prod.tfvars" -auto-approve

    - name: Output Infrastructure URLs
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform output